name: reinforce
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.12
  - pip
  - pip:
      - ipykernel
      - numpy
      - matplotlib
      - jax
      - optax
      - flax
      - jaxtyping
